### ISSUE TITLE
Re-export some built-ins (e.g. type-level list TyCons)

### ISSUE THREAD

**Issue by sheaf** [sheaf/ghc-tcplugin-api#3]
Some built-in things such as type-level lists, `Maybe`, `Nat`, `Symbol`, tuples... should be re-exported, and the documentation should clarify that these should be used directly instead of the usual name resolution process.

**Comment by sheaf** [comment]
Also utility functions to deal with type literals, e.g. `isStrLitTy`, `isNumLitTy` (perhaps `isCharLitTy`?).

**Comment by edsko** [comment]
Why is only part of `CoreExpr` (== `Expr CoreBndr`) exported? Feels like quite a deliberate decision, but I need more (`App`, `Lit`, maybe more), as well as `Literal(LitString)` (and possibly others).

**Comment by edsko** [comment]
Maybe a basic `FastString` API? Currently needing at least `fastStringToByteString` (to construct a `Literal`) -- which is actually a nice candidate for the lib because that API changes in various ghc versions.

**Comment by sheaf** [comment]
`GHC.Core.Make` is re-exported, is that not enough?

**Comment by edsko** [comment]
Oh! Possibly. Let me check.

**Comment by edsko** [comment]
Yes, it suffices. `MonadThings` instance might be handy though to be able to some of the functions in that module (https://github.com/well-typed/large-anon/blob/main/src/Data/Record/Anonymous/Plugin/GhcTcPluginAPI.hs#L30-L33).

**Comment by edsko** [comment]
`mkIntExpr` and co change between ghc versions though (`DynFlags` versus `Platform` argument). Might be worth abstracting over that (probably most useful would be `mkUncheckedIntExpr`, which isn't available in 8.8 at all).

**Comment by sheaf** [comment]
Closed with 65f5aad.
